import { describe, it, expect } from 'vitest'
import { tailwindV4Formatter } from './tailwind-v4.js'
import type { Dictionary, TransformedToken } from 'style-dictionary/types'

// Minimal mock for the dictionary argument — only allTokens is used by the formatter
function makeDictionary(tokens: Partial<TransformedToken>[]): Dictionary {
  return { allTokens: tokens as TransformedToken[] } as unknown as Dictionary
}

const UNUSED = {} as never

describe('tailwindV4Formatter', () => {
  it('wraps output in an @theme block with a header comment', () => {
    const output = tailwindV4Formatter({
      dictionary: makeDictionary([]),
      platform: UNUSED,
      options: UNUSED,
      file: UNUSED,
    })
    expect(output).toContain('/* Auto-generated by figma-variables-style-dictionary */')
    expect(output).toContain('@theme {')
    expect(output).toContain('}')
  })

  it('maps Colors/* tokens to --color-* with var() references', () => {
    const output = tailwindV4Formatter({
      dictionary: makeDictionary([
        {
          path: ['Colors', 'grey', '50'],
          name: 'colors-grey-50',
          value: '#f8f8f8',
          $type: 'color',
        },
        {
          path: ['Colors', 'foundation', 'brand', 'default'],
          name: 'colors-foundation-brand-default',
          value: '#2b5dff',
          $type: 'color',
        },
      ]),
      platform: UNUSED,
      options: UNUSED,
      file: UNUSED,
    })
    expect(output).toContain('--color-grey-50: var(--colors-grey-50);')
    expect(output).toContain(
      '--color-foundation-brand-default: var(--colors-foundation-brand-default);',
    )
  })

  it('maps Dimensions/spacing/* tokens to --spacing-* with actual values', () => {
    const output = tailwindV4Formatter({
      dictionary: makeDictionary([
        {
          path: ['Dimensions', 'spacing', '4'],
          name: 'dimensions-spacing-4',
          value: '16px',
          $type: 'number',
        },
        {
          path: ['Dimensions', 'spacing', '0'],
          name: 'dimensions-spacing-0',
          value: '0px',
          $type: 'number',
        },
      ]),
      platform: UNUSED,
      options: UNUSED,
      file: UNUSED,
    })
    expect(output).toContain('--spacing-4: 16px;')
    expect(output).toContain('--spacing-0: 0px;')
  })

  it('maps Dimensions/breakpoints/* tokens to --breakpoint-*', () => {
    const output = tailwindV4Formatter({
      dictionary: makeDictionary([
        {
          path: ['Dimensions', 'breakpoints', 'lg'],
          name: 'dimensions-breakpoints-lg',
          value: '1024px',
          $type: 'number',
        },
      ]),
      platform: UNUSED,
      options: UNUSED,
      file: UNUSED,
    })
    expect(output).toContain('--breakpoint-lg: 1024px;')
  })

  it('maps Borders/border-radius/* tokens to --radius-*', () => {
    const output = tailwindV4Formatter({
      dictionary: makeDictionary([
        {
          path: ['Borders', 'border-radius', 'rounded-md'],
          name: 'borders-border-radius-rounded-md',
          value: '6px',
          $type: 'number',
        },
        {
          path: ['Borders', 'border-radius', 'rounded-full'],
          name: 'borders-border-radius-rounded-full',
          value: '9999px',
          $type: 'number',
        },
      ]),
      platform: UNUSED,
      options: UNUSED,
      file: UNUSED,
    })
    expect(output).toContain('--radius-rounded-md: 6px;')
    expect(output).toContain('--radius-rounded-full: 9999px;')
  })

  it('maps Borders/border-width/* tokens to --border-width-*', () => {
    const output = tailwindV4Formatter({
      dictionary: makeDictionary([
        {
          path: ['Borders', 'border-width', 'border'],
          name: 'borders-border-width-border',
          value: '1px',
          $type: 'number',
        },
      ]),
      platform: UNUSED,
      options: UNUSED,
      file: UNUSED,
    })
    expect(output).toContain('--border-width-border: 1px;')
  })

  it('maps Effects/opacity/* tokens to --opacity-*', () => {
    const output = tailwindV4Formatter({
      dictionary: makeDictionary([
        {
          path: ['Effects', 'opacity', 'opacity-50'],
          name: 'effects-opacity-50',
          value: '0.5',
          $type: 'number',
        },
      ]),
      platform: UNUSED,
      options: UNUSED,
      file: UNUSED,
    })
    expect(output).toContain('--opacity-opacity-50: 0.5;')
  })

  it('maps Effects/blur/* tokens to --blur-*', () => {
    const output = tailwindV4Formatter({
      dictionary: makeDictionary([
        {
          path: ['Effects', 'blur', 'blur-md'],
          name: 'effects-blur-md',
          value: '12px',
          $type: 'number',
        },
      ]),
      platform: UNUSED,
      options: UNUSED,
      file: UNUSED,
    })
    expect(output).toContain('--blur-blur-md: 12px;')
  })

  it('maps Typography tokens to the correct --property- prefixes', () => {
    const output = tailwindV4Formatter({
      dictionary: makeDictionary([
        {
          path: ['Typography', 'font-family', 'bayernwerk'],
          name: 'typography-font-family-bayernwerk',
          value: 'Polo 11',
          $type: 'string',
        },
        {
          path: ['Typography', 'font-size', 'text-base'],
          name: 'typography-font-size-text-base',
          value: '16',
          $type: 'number',
        },
        {
          path: ['Typography', 'font-weight', 'regular'],
          name: 'typography-font-weight-regular',
          value: 'Regular',
          $type: 'string',
        },
        {
          path: ['Typography', 'line-height', 'body'],
          name: 'typography-line-height-body',
          value: '24',
          $type: 'number',
        },
      ]),
      platform: UNUSED,
      options: UNUSED,
      file: UNUSED,
    })
    expect(output).toContain('--font-bayernwerk: Polo 11;')
    expect(output).toContain('--font-size-text-base: 16;')
    expect(output).toContain('--font-weight-regular: Regular;')
    expect(output).toContain('--leading-body: 24;')
  })

  it('outputs resolved color values when resolvedValues option is true', () => {
    const output = tailwindV4Formatter({
      dictionary: makeDictionary([
        {
          path: ['Colors', 'grey', '50'],
          name: 'colors-grey-50',
          value: '#f8f8f8',
          $type: 'color',
        },
        {
          path: ['Colors', 'foundation', 'brand', 'default'],
          name: 'colors-foundation-brand-default',
          value: '#003f8a',
          $type: 'color',
        },
      ]),
      platform: UNUSED,
      options: { resolvedValues: true },
      file: UNUSED,
    })
    expect(output).toContain('--color-grey-50: #f8f8f8;')
    expect(output).toContain('--color-foundation-brand-default: #003f8a;')
    expect(output).not.toContain('var(--')
  })

  it('skips Dimensions/sizing/* (no Tailwind v4 equivalent)', () => {
    const output = tailwindV4Formatter({
      dictionary: makeDictionary([
        {
          path: ['Dimensions', 'sizing', 'size-4'],
          name: 'dimensions-sizing-size-4',
          value: '16px',
          $type: 'number',
        },
      ]),
      platform: UNUSED,
      options: UNUSED,
      file: UNUSED,
    })
    expect(output).not.toContain('sizing')
  })

  it('skips tokens with unrecognised top-level groups', () => {
    const output = tailwindV4Formatter({
      dictionary: makeDictionary([
        {
          path: ['Overlays', 'white', 'alpha-5'],
          name: 'overlays-white-alpha-5',
          value: 'rgba(255,255,255,0.05)',
          $type: 'color',
        },
      ]),
      platform: UNUSED,
      options: UNUSED,
      file: UNUSED,
    })
    expect(output).not.toContain('overlays')
  })
})
