/**
 * Style Dictionary formatter: Tailwind v4 @theme CSS output (TICKET-010)
 *
 * Generates a `tailwind.css` file with a Tailwind v4 `@theme {}` block.
 * Tailwind v4 reads CSS custom properties under `@theme` at build time to
 * create its utility classes.
 *
 * Color tokens reference the existing CSS custom properties (`var(--...)`) so
 * that a single Tailwind config works with runtime brand switching. All other
 * token categories use their transformed values directly.
 *
 * Token path → Tailwind v4 CSS property prefix mapping:
 *   Colors/*                   → --color-
 *   Dimensions/spacing/*       → --spacing-
 *   Dimensions/breakpoints/*   → --breakpoint-
 *   Borders/border-radius/*    → --radius-
 *   Borders/border-width/*     → --border-width-
 *   Effects/opacity/*          → --opacity-
 *   Effects/blur/*             → --blur-
 *   Typography/font-family/*   → --font-
 *   Typography/font-size/*     → --font-size-
 *   Typography/font-weight/*   → --font-weight-
 *   Typography/line-height/*   → --leading-
 *
 * Consuming project:
 *   @import './build/tailwind/tailwind.css';
 */

import type { FormatFn } from 'style-dictionary/types'

/**
 * Sanitize a path segment for use in a CSS custom property name.
 * Mirrors the segment normalization in the name/kebab-deduped transform.
 */
function toKebab(segment: string): string {
  return segment
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
}

/**
 * Maps a token path to a [cssPropertyPrefix, keyStartIndex] pair.
 * Returns null for paths that don't map to a Tailwind v4 @theme property.
 */
function getPropertyPrefix(path: string[]): [string, number] | null {
  const [top, sub] = path
  switch (top) {
    case 'Colors':
      return ['--color-', 1]
    case 'Dimensions':
      if (sub === 'spacing') return ['--spacing-', 2]
      if (sub === 'breakpoints') return ['--breakpoint-', 2]
      // sizing has no direct Tailwind v4 equivalent; omit
      return null
    case 'Borders':
      if (sub === 'border-radius') return ['--radius-', 2]
      if (sub === 'border-width') return ['--border-width-', 2]
      return null
    case 'Effects':
      if (sub === 'opacity') return ['--opacity-', 2]
      if (sub === 'blur') return ['--blur-', 2]
      return null
    case 'Typography':
      if (sub === 'font-family') return ['--font-', 2]
      if (sub === 'font-size') return ['--font-size-', 2]
      if (sub === 'font-weight') return ['--font-weight-', 2]
      if (sub === 'line-height') return ['--leading-', 2]
      return null
    default:
      return null
  }
}

export const tailwindV4Formatter: FormatFn = ({ dictionary, options }) => {
  const lines: string[] = []

  for (const token of dictionary.allTokens) {
    const result = getPropertyPrefix(token.path)
    if (!result) continue

    const [prefix, keyStart] = result
    const suffix = token.path.slice(keyStart).map(toKebab).join('-')
    const property = `${prefix}${suffix}`

    // In DTCG mode (usesDtcg), Style Dictionary stores the transformed value in
    // token.$value rather than token.value — mirror the SD v4 built-in format pattern.
    const rawValue = options.usesDtcg ? token.$value : token.value

    // Colors reference the existing CSS custom property for runtime brand switching.
    // When resolvedValues is true (per-brand static builds), use the actual value instead.
    const resolvedValues = (options as { resolvedValues?: boolean }).resolvedValues ?? false
    const value =
      token.path[0] === 'Colors' && !resolvedValues ? `var(--${token.name})` : String(rawValue)

    lines.push(`  ${property}: ${value};`)
  }

  return [
    '/* Auto-generated by figma-variables-style-dictionary */',
    '@theme {',
    ...lines,
    '}',
    '',
  ].join('\n')
}
